[package]
name = "mdrend"
version = "0.1.0"
authors = ["Elvis Dedic <elvisdedic@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.21.0"
clap = "2.33.0"
pulldown-cmark = "0.6.1"
